name: Build Chrome Proxy Manager

on:
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "Chrome_Proxy_Manager" app.py

      - name: Prepare release folder
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path release | Out-Null
          Copy-Item "dist/Chrome_Proxy_Manager.exe" release/
          if (Test-Path "profiles.json") { Copy-Item "profiles.json" release/ }
          if (Test-Path "proxies.txt") { Copy-Item "proxies.txt" release/ }

      - name: Zip artifacts
        shell: pwsh
        run: |
          Compress-Archive -Path release/* -DestinationPath Chrome_Proxy_Manager.zip -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Chrome_Proxy_Manager
          path: Chrome_Proxy_Manager.zip
