name: Build Chrome Proxy Tool

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pyinstaller selenium

    - name: Build exe
      run: |
        python build_exe.py

    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
        name: ChromeProxyTool
        path: dist/*.exe
